// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlsvucfgeimcwfvugklp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhsc3Z1Y2ZnZWltY3dmdnVna2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDY5ODAsImV4cCI6MjA1NzYyMjk4MH0._TRlJzgg0wk-OXBcqPifZR4Jl_6WP0DtVWL0QRHUwFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);